export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    ADMIN_DASHBOARD: '/admin',
    ADMIN_ANALYSTS: '/admin/analistas',
    ADMIN_ANALYST_FORM: '/admin/analistas/nuevo',
    ADMIN_IMPORT: '/admin/importar',
    ADMIN_PROTESTS: '/admin/protestos',
    ADMIN_AUDIT: '/admin/auditoria',
    ADMIN_SOLICITUDES: '/admin/solicitudes',
    ANALYST_DASHBOARD: '/analista',
    ANALYST_SEARCH: '/analista/consulta',
    ANALYST_HISTORY: '/analista/historial',
    ANALYST_SOLICITUDES: '/analista/solicitudes',
}
